# Tap Repsitories
tap "homebrew/bundle"
tap "homebrew/cask-fonts"

# Productivity
cask "rectangle"

# Fonts
cask "font-jetbrains-mono-nerd-font"

# Entertainment
cask "spotify"

# Terminal Emulators
cask "kitty"

# Shell Tools
brew "gh"
brew "exa"
brew "git-delta"

# Shells
brew "fish"

# Browsers
cask "google-chrome"
